name: Build Workflow

on:
  workflow_call:
    inputs:
      asset_suffix:
        description: 'Suffix to append to asset names'
        required: false
        default: ''
        type: string
    
jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            asset_name: neoxtractor-linux
          - os: windows-latest
            arch: x64
            asset_name: neoxtractor-windows
          - os: macos-latest
            arch: x64
            asset_name: neoxtractor-macos-x64
          - os: macos-latest
            arch: arm64
            asset_name: neoxtractor-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: ${{ matrix.arch }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.7.3'
          
      - name: Install dependencies
        run: |
          uv venv
          uv pip install pyinstaller --system
          uv sync

      - name: Build with PyInstaller
        run: |
          pyinstaller main.spec
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}${{ inputs.asset_suffix }}
          path: dist/main/
          compression-level: 9