name: Code Linting

on:
  push:
    branches: [ rewrite-qt6 ]
  pull_request:
    branches: [ rewrite-qt6 ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.7.4'
          
      - name: Install dependencies
        run: |
          uv venv
          uv sync --locked
          uv pip install pylint
      
      - name: Run PyLint
        run: |
          uv run pylint --rcfile=pylintrc --output-format=github $(git ls-files '*.py')
        continue-on-error: true